---
- name: Deploy Application Profile
  hosts: apic
  connection: local
  gather_facts: no
  vars:
    apic_info: &apic_info
      host: "{{ apic_ip }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      validate_certs: no

  tasks:
    - name: Add a new contract to EPG binding
      aci_epg_to_contract:
        <<: *apic_info
        tenant: Sales
        ap: eCommerce_AP
        epg: "{{ item.epg }}"
        contract: WebServices_Ct
        contract_type: "{{ item.contract_type }}"
        state: present
      with_items:
        - epg: Web_EPG
          contract_type: consumer
        - epg: App_EPG
          contract_type: provider