[apic]
apic1 ansible_host=sandboxapicdc.cisco.com

[apic:vars]
apic= sandboxapicdc.cisco.com
apic_ip= 192.168.10.1
apic_username= "admin"
apic_password= "ciscopsdt"
ansible_connection= local
ansible_python_interpreter=/usr/bin/python3

[vcenter]
vcenter1 ansible_host=192.168.61.35

[vcenter:vars]
vcenter_hostname = vcenter
vcenter_username = administrator@vsphere.local
vcenter_password = T0ps3cr3t2@
ansible_connection= local
ansible_python_interpreter=/usr/bin/python

[esx]
esx1 ansible_host=192.168.61.55

[esx:vars]
esxi_hostname = 192.168.61.55
