---
- name: Configure IPN Routers
  hosts:
    - ios-xe-azure
  gather_facts: no


  tasks:
  - name: Enable LLDP service
    ios_lldp:
      state: present

  - name: run show version on remote devices
    ios_command:
      commands: show lldp neighbors
    register: output

  - name: Display show lldp neighbors output
    debug:
      msg: "{{output}}"
