---
- name: 02. Configure VRF
  hosts:
    - ios-xe-azure
  gather_facts: no


  tasks:
  - name: configure a vrf named management
    ios_vrf:
      name: vrf context IPN-1
      description: VRF for IPN-1

  - name: Run show lldp neighbors on remote devices
    ios_command:
      commands: show vrf
    register: output

  - name: Display show lldp neighbors output
    debug:
      msg: "{{output}}"
