---
- name: 02. Configure VRF
  hosts:
    - ios-xe-azure
  gather_facts: no


  tasks:
  - name: Configure a vrf
    ios_vrf:
      name: IPN-1
      description: VRF for IPN-1

  - name: Run show vrf on remote devices
    ios_command:
      commands: show vrf
    register: output

  - name: Display show vrf output
    debug:
      msg: "{{output}}"
